/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package opening;

import dao.forgetPassDao;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    forgetPassDao fg = new forgetPassDao();
    Color notEdit = new Color(204, 204, 204);
    Color Edit = new Color(255, 255, 255);

    public ForgotPassword() {
        initComponents();
        init();
    }

    public void init() {
        //phonesign.setBackground(notEdit);
        //fpass.setBackground(notEdit);
        phonesign.setEditable(false);
        fpass.setEditable(false);
        jButton1.setEnabled(false);
        jButton1.setColor1(notEdit);
        jButton1.setColor2(notEdit);

        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        jRadioButton1.setSelected(true);
        jLabel9.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (emailValid()) {
                    if (jRadioButton1.isSelected()) {
                        if (fg.isEmailexistj(jTextField1.getText())) {
                            jTextField1.setEditable(false);
                            //phonesign.setBackground(Edit);
                            phonesign.setEditable(true);
                            //fpass.setBackground(Edit);
                            fpass.setEditable(true);
                            jButton1.setEnabled(true);
                            jButton1.setColor1(new Color(3, 36, 117));
                            jButton1.setColor2(new Color(3, 36, 117));
                        }
                    } else {
                        if (fg.isEmailexistr(jTextField1.getText())) {

                            jTextField1.setEditable(false);
                            //phonesign.setBackground(Edit);
                            phonesign.setEditable(true);
                            //fpass.setBackground(Edit);
                            fpass.setEditable(true);
                            jButton1.setEnabled(true);
                            jButton1.setColor1(new Color(3, 36, 117));
                            jButton1.setColor2(new Color(3, 36, 117));
                        }
                    }
                }
            }
        });
        jLabel9.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                jLabel9.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
        jLabel3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Login frm = new Login();
                frm.setVisible(true);
                dispose();
            }
        });
        jLabel3.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                jLabel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
        close.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
            }
        });
        close.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                close.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jTextField1 = new try__.TextField();
        phonesign = new try__.TextField();
        fpass = new careerpathx.PasswordField();
        jRadioButton1 = new try__.RadioButtonCustom();
        jRadioButton2 = new try__.RadioButtonCustom();
        jLabel9 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new try__.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setLabelText("Enter your Email  Address :");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 330, -1));

        phonesign.setLabelText("Enter your Phone number :");
        phonesign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonesignKeyPressed(evt);
            }
        });
        getContentPane().add(phonesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 330, -1));

        fpass.setLabelText("New Password :");
        getContentPane().add(fpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 330, -1));

        bg.add(jRadioButton1);
        jRadioButton1.setText("Job Seeker");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 120, -1));

        bg.add(jRadioButton2);
        jRadioButton2.setText("Recruiter");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/search.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, -1, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/fpass.png"))); // NOI18N
        getContentPane().add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 130, 120));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("Create Your Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jButton1.setText("Enter");
        jButton1.setColor1(new java.awt.Color(3, 36, 117));
        jButton1.setColor2(new java.awt.Color(3, 36, 117));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 330, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-back.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-cross-30.png"))); // NOI18N
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel9MouseClicked

    private void phonesignKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonesignKeyPressed
        // TODO add your handling code here:
        String phn = phonesign.getText();
        int l = phn.length();
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
            if (l < 11) {
                phonesign.setEditable(true);
            } else {
                phonesign.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                phonesign.setEditable(true);
            } else {
                phonesign.setEditable(false);
            }
        }
    }//GEN-LAST:event_phonesignKeyPressed
    public boolean isEmpty() {
        if (phonesign.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the Phone Number", "Invalid", 2);
            return false;
        } else if (fpass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter your new Password", "Invalid", 2);
            return false;
        }
        return true;
    }

    public boolean emailValid() {
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the Email Address", "Invalid", 2);
            return false;
        } else if (!jTextField1.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address", "Invalid", 2);
            return false;
        }
        return true;

    }
    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        jLabel9.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel9MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (isEmpty()) {
            if (jRadioButton1.isSelected()) {
                String email = jTextField1.getText();
                String newans = phonesign.getText();
                if (fg.getsphn(email, newans)) {
                    String pass = String.valueOf(fpass.getPassword());
                    fg.newspass(email, pass);
                    new Login().setVisible(true);
                    this.dispose();
                }
            } else {
                String email = jTextField1.getText();
                String newans = phonesign.getText();
                if (fg.getrphn(email, newans)) {
                    String pass = String.valueOf(fpass.getPassword());
                    fg.newrpass(email, pass);
                    new Login().setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JLabel close;
    private careerpathx.PasswordField fpass;
    private try__.ButtonGradient jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private try__.RadioButtonCustom jRadioButton1;
    private try__.RadioButtonCustom jRadioButton2;
    private try__.TextField jTextField1;
    private try__.TextField phonesign;
    private rojerusan.RSLabelImage rSLabelImage1;
    // End of variables declaration//GEN-END:variables
}
