/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package opening;

import Connection.Myconnection;
import drawer1.jobseeker;
import drawer.Admin;
import drawer1.job_view;
import drawer2.Recruiter;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Hp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        init();
        jButton3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                ForgotPassword fpframe = new ForgotPassword();
                fpframe.setVisible(true);
                fpframe.pack();
                fpframe.setLocationRelativeTo(null);
                dispose();
            }
        });
        jButton3.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                jButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
        jLabel3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Homapage frame = new Homapage();
                frame.setVisible(true);
                frame.pack();
                frame.setLocationRelativeTo(null);
                dispose();
            }
        });
        jLabel3.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                jLabel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
        close.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
            }
        });
        close.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                close.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
    }

    public void init() {
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(jRadioButton3);
        jRadioButton1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        loginpass = new careerpathx.PasswordField();
        email = new try__.TextField();
        jRadioButton1 = new try__.RadioButtonCustom();
        jRadioButton2 = new try__.RadioButtonCustom();
        jRadioButton3 = new try__.RadioButtonCustom();
        rSPanelCircleImage1 = new rojerusan.RSPanelCircleImage();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JLabel();
        jButton1 = new try__.ButtonGradient();
        jButton2 = new try__.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpass.setLabelText("Password :");
        loginpass.setShowAndHide(true);
        getContentPane().add(loginpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 330, -1));

        email.setLabelText("Email : ");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 330, -1));

        bg.add(jRadioButton1);
        jRadioButton1.setText("Job Seeker");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 100, -1));

        bg.add(jRadioButton2);
        jRadioButton2.setText("Recruiter");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        bg.add(jRadioButton3);
        jRadioButton3.setText("Admin");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 320, 70, -1));

        rSPanelCircleImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-user-100.png"))); // NOI18N
        getContentPane().add(rSPanelCircleImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 90, 90));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 350, 10));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 150, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Forgot Password ?");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 110, -1));

        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setText("Login");
        jButton1.setColor1(new java.awt.Color(3, 36, 117));
        jButton1.setColor2(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 330, 40));

        jButton2.setText("Create new account");
        jButton2.setColor1(new java.awt.Color(15, 145, 15));
        jButton2.setColor2(new java.awt.Color(5, 206, 85));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 330, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-back.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-cross-30.png"))); // NOI18N
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (email.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the email");
        } else if (!email.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address", "Invalid", 2);
        } else if (loginpass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the password");
        } else {
            if (jRadioButton3.isSelected()) {
                String name = email.getText();
                String pass = String.valueOf(loginpass.getPassword());
                try {
                    Connection con = (Connection) Myconnection.getConnection();
                    PreparedStatement ps;
                    ps = con.prepareStatement("select * from admin where email =? and pass =?");
                    ps.setString(1, name);
                    ps.setString(2, pass);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        Admin hpage = new Admin();
                        hpage.setVisible(true);
                        hpage.adname.setText("Welcome home, " + name + "!");
                        hpage.pack();
                        hpage.setLocationRelativeTo(null);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Incorrect", "login failed", 1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (jRadioButton1.isSelected()) {
                String name = email.getText();
                String pass = String.valueOf(loginpass.getPassword());
                try {
                    Connection con = (Connection) Myconnection.getConnection();
                    PreparedStatement ps;
                    ps = con.prepareStatement("select * from jseeker where semail = ? and spass = ?");
                    ps.setString(1, name);
                    ps.setString(2, pass);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        jobseeker hpage = new jobseeker();
                        hpage.setVisible(true);
                        hpage.pack();
                        hpage.setLocationRelativeTo(null);

                        // Retrieve jobseeker information from the ResultSet
                        int id = rs.getInt("id");
                        String email = rs.getString("semail");
                        String fullName = rs.getString("sname");
                        String phoneNumber = rs.getString("sphn");
                        String address = rs.getString("sadd");
                        String dob = rs.getString("sdob");
                        String gender = rs.getString("sgender");
                        byte[] dp = rs.getBytes("Profile_Picture"); // Corrected variable type to byte[]
                        byte[] cv = rs.getBytes("CV"); // Corrected variable type to byte[]
                        
                        // You can retrieve other information as well
                        // Set the information in the jobseeker frame
                        hpage.userMail.setText(email);
                        job_view.getname(email);
                        hpage.emailsign.setText(email);
                        hpage.password.setText(pass);
                        hpage.userId.setText(Integer.toString(id));
                        hpage.Fullname.setText(fullName);
                        hpage.phoneNumber.setText(phoneNumber);
                        hpage.userAddress.setText(address);
                          Date dobDate = null;
                        try {
                            dobDate = new SimpleDateFormat("yyyy-MM-dd").parse(dob); // Parse the date string from the database
                        } catch (ParseException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        hpage.userDOB.setDate(dobDate);
                        hpage.userGender.setSelectedItem(gender);

                        // Set the profile picture if it exists
                        if (dp != null) {
                            ImageIcon profilePicture = new ImageIcon(dp);
                             hpage.profilePictureLabel.setIcon(profilePicture);
                        }
                        if (cv != null) {
                            ImageIcon profilePicture = new ImageIcon(cv);
                             hpage.cv.setIcon(profilePicture);
                        }

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Incorrect", "Login Failed", 1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (jRadioButton2.isSelected()) {
                String name = email.getText();
                String pass = String.valueOf(loginpass.getPassword());
                try {
                    Connection con = (Connection) Myconnection.getConnection();
                    PreparedStatement ps;
                    ps = con.prepareStatement("select * from recruiter where remail = ? and rpass = ?");
                    ps.setString(1, name);
                    ps.setString(2, pass);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        int r_id = rs.getInt("rid");
                        String rm=rs.getString("remail");
                        Recruiter hpage = new Recruiter();
                        hpage.setVisible(true);
                        hpage.setRid(r_id,rm);
                        hpage.populatetable();
                        hpage.pack();
                        hpage.setLocationRelativeTo(null);
                        // Set the rid in the recruiter page
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Incorrect", "Login Failed", 1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            Signup Signupframe = new Signup();
            Signupframe.setVisible(true);
            Signupframe.pack();
            Signupframe.setLocationRelativeTo(null);
            this.dispose();
        } else if (jRadioButton2.isSelected()) {
            Signup2 Signupframe = new Signup2();
            Signupframe.setVisible(true);
            Signupframe.pack();
            Signupframe.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JLabel close;
    private try__.TextField email;
    private try__.ButtonGradient jButton1;
    private try__.ButtonGradient jButton2;
    private javax.swing.JLabel jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private try__.RadioButtonCustom jRadioButton1;
    private try__.RadioButtonCustom jRadioButton2;
    private try__.RadioButtonCustom jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private careerpathx.PasswordField loginpass;
    private rojerusan.RSPanelCircleImage rSPanelCircleImage1;
    // End of variables declaration//GEN-END:variables
}
