/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drawer1;

import Connection.Myconnection;
import careerpathx.ScrollBarCustom;
import details.com_info;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JScrollBar;
//github
/**
 *
 * @author Hp
 */
public class display_companies extends javax.swing.JPanel {

    /**
     * Creates new form display_companies
     */
    ComView jblist = null;

    public display_companies() {
        initComponents();
        set_job_combo();
        update_list();

        JScrollBar verticalScrollBar = ScrollView.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
        ScrollView.setVerticalScrollBar(new ScrollBarCustom());

    }

    public void set_job_combo() {
        cty.removeAll();
        cty.addItem("");
        try {
            Connection con = Myconnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT company_type FROM companies");
            while (rs.next()) {
                cty.addItem(rs.getString("company_type"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        lc.removeAll();
        lc.addItem("");
        try {
            Connection con = Myconnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT location FROM companies");
            while (rs.next()) {
                lc.addItem(rs.getString("location"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        in.removeAll();
        in.addItem("");
        try {
            Connection con = Myconnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT industry FROM companies");
            while (rs.next()) {
                in.addItem(rs.getString("industry"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_list() {
        String CT = (String) (cty.getSelectedIndex() == -1 ? "" : cty.getItemAt(cty.getSelectedIndex()));
        String LC = (String) (lc.getSelectedIndex() == -1 ? "" : lc.getItemAt(lc.getSelectedIndex()));
        String IN = (String) (in.getSelectedIndex() == -1 ? "" : in.getItemAt(in.getSelectedIndex()));
        var jobs = new ArrayList<com_info>();

        try {
            Connection con = Myconnection.getConnection();
            String query = "SELECT * FROM companies WHERE company_type LIKE ? AND location LIKE ? AND industry LIKE ? ORDER BY company_type ASC";
            var st = con.prepareStatement(query);
            st.setString(1, CT.equals("") ? "%" : "%" + CT + "%");
            st.setString(2, LC.equals("") ? "%" : "%" + LC + "%");
            st.setString(3, IN.equals("") ? "%" : "%" + IN + "%");

            var rs = st.executeQuery();
            while (rs.next()) {
                jobs.add(new com_info(rs));
            }
            update_res_panel(new ComView(jobs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_res_panel(ComView bv) {
        if (jblist != null) {
            ScrollView.getViewport().remove(jblist);
        }
        ScrollView.getViewport().add(bv);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cty = new try__.Combobox();
        lc = new try__.Combobox();
        in = new try__.Combobox();
        ScrollView = new javax.swing.JScrollPane();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();

        setBackground(new java.awt.Color(161, 161, 253));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-tune-16.png"))); // NOI18N
        jLabel1.setText("All Filters");

        cty.setLabeText("Company Type :");

        lc.setLabeText("Location :");

        in.setLabeText("Industry :");

        rSButtonMetro1.setBackground(new java.awt.Color(71, 71, 246));
        rSButtonMetro1.setText("Search");
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cty, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(lc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addComponent(ScrollView, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(cty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(ScrollView, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        update_list();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollView;
    private try__.Combobox cty;
    private try__.Combobox in;
    private javax.swing.JLabel jLabel1;
    private try__.Combobox lc;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables
}
