/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drawer1;

import details.job_info;
import java.util.ArrayList;
import javax.swing.JScrollBar;
import Connection.Myconnection;
import careerpathx.ScrollBarCustom;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import try__.Combobox;

/**
 *
 * @author Hp
 */
public class display_jobs extends javax.swing.JPanel {

    /**
     * Creates new form display_jobs
     */
    JobView jblist = null;

    public display_jobs() {

        initComponents();
        set_job_combo();
        update_list();

        JScrollBar verticalScrollBar = ScrollView.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
        ScrollView.setVerticalScrollBar(new ScrollBarCustom());
        reset.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                jt.setSelectedIndex(-1);
                skl.setText("");
                cmp.setText("");
                lctn.setText("");
                update_list();
            }
        });
        reset.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                reset.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
    }

    public void set_job_combo() {
        jt.removeAll();
        jt.addItem("");
        try {
            Connection con = Myconnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT job_title FROM jobs");
            while (rs.next()) {
                jt.addItem(rs.getString("job_title"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_list() {
        String JT = (String) (jt.getSelectedIndex() == -1 ? "" : jt.getItemAt(jt.getSelectedIndex()));
        String SKL = skl.getText();
        String CMP = cmp.getText();
        String LCTN = lctn.getText();
        var jobs = new ArrayList<job_info>();

        try {
            Connection con = Myconnection.getConnection();
            String query = "SELECT * FROM jobs WHERE job_title LIKE ? AND qualification LIKE ? AND company LIKE ? AND location LIKE ? ORDER BY company ASC";
            var st = con.prepareStatement(query);
            st.setString(1, JT.equals("") ? "%" : "%" + JT + "%");
            st.setString(2, SKL.equals("") ? "%" : "%" + SKL + "%");
            st.setString(3, CMP.equals("") ? "%" : "%" + CMP + "%");
            st.setString(4, LCTN.equals("") ? "%" : "%" + LCTN + "%");

            var rs = st.executeQuery();
            while (rs.next()) {
                jobs.add(new job_info(rs));
            }
            update_res_panel(new JobView(jobs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_res_panel(JobView bv) {
        if (jblist != null) {
            ScrollView.getViewport().remove(jblist);
        }
        ScrollView.getViewport().add(bv);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollView = new javax.swing.JScrollPane();
        materialButton1 = new necesario.MaterialButton();
        reset = new rojerusan.RSPanelImage();
        lctn = new try__.TextField();
        cmp = new try__.TextField();
        skl = new try__.TextField();
        jt = new try__.Combobox();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollView.setBackground(new java.awt.Color(204, 204, 255));
        ScrollView.setForeground(new java.awt.Color(255, 255, 255));
        add(ScrollView, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 1530, 550));

        materialButton1.setBackground(new java.awt.Color(153, 0, 153));
        materialButton1.setForeground(new java.awt.Color(255, 255, 255));
        materialButton1.setText("Find");
        materialButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });
        add(materialButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 60, 150, 50));

        reset.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-refresh-48.png"))); // NOI18N

        javax.swing.GroupLayout resetLayout = new javax.swing.GroupLayout(reset);
        reset.setLayout(resetLayout);
        resetLayout.setHorizontalGroup(
            resetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        resetLayout.setVerticalGroup(
            resetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 60, -1, -1));

        lctn.setLabelText("Location");
        add(lctn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 270, 47));

        cmp.setLabelText("Company");
        add(cmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 60, 300, 47));

        skl.setLabelText("Skills");
        add(skl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 316, 47));

        jt.setLabeText("Job Title");
        add(jt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 260, 47));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/we are hiring!.png"))); // NOI18N
        add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        // TODO add your handling code here:
        update_list();
    }//GEN-LAST:event_materialButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollView;
    private try__.TextField cmp;
    private try__.Combobox jt;
    private try__.TextField lctn;
    private necesario.MaterialButton materialButton1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSPanelImage reset;
    private try__.TextField skl;
    // End of variables declaration//GEN-END:variables
}
