/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drawer1;

import details.job_info;
import java.awt.Color;
import First.WrapLayout;
import java.awt.Rectangle;
import java.util.ArrayList;

/**
 *
 * @author Hp
 */
public class JobView extends javax.swing.JPanel {

    /**
     * Creates new form JobView
     */
    ArrayList<job_info> job_d;
    int rows = 0;
    static final Rectangle pnl = new Rectangle(280, 420);

    public JobView(ArrayList<job_info> job_d) {
        initComponents();
        this.job_d = job_d;
        rows = Math.ceilDiv(job_d.size(), 3);
        this.setLayout(new WrapLayout(WrapLayout.LEADING, 80, 80));
        var grid = this;
        //this.setBackground(Color.white);
        for (job_info bk: job_d) {
            this.add(new job_view(bk));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
