/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drawer1;

import Connection.Myconnection;
import careerpathx.ScrollBarCustom;
import details.service_info;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JScrollBar;

/**
 *
 * @author Hp
 */
public class services extends javax.swing.JPanel {

    /**
     * Creates new form services
     */
    ServiceView jblist = null;
    public services() {
        initComponents();
        update_list();
        JScrollBar verticalScrollBar = ScrollView.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
        ScrollView.setVerticalScrollBar(new ScrollBarCustom());
    }
public void update_list() {
        var jobs = new ArrayList<service_info>();

        try {
            Connection con = Myconnection.getConnection();
            String query = "SELECT * FROM services ORDER BY title ASC";
            var st = con.prepareStatement(query);

            var rs = st.executeQuery();
            while (rs.next()) {
                jobs.add(new service_info(rs));
            }
            update_res_panel(new ServiceView(jobs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void update_res_panel(ServiceView bv) {
        if (jblist != null) {
            ScrollView.getViewport().remove(jblist);
        }
        ScrollView.getViewport().add(bv);
        this.validate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollView = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(1203, 696));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollView, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollView, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollView;
    private javax.swing.JButton jButton56;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
