/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drawer1;

import details.service_info;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import try__.MessageDialog;

/**
 *
 * @author Hp
 */
public class service_view extends javax.swing.JPanel {

    /**
     * Creates new form service_view
     */
    service_info ji;

    public service_view(service_info ji) {

        initComponents();
        this.ji = ji;
        textArea1.setText(ji.des);
        ti.setText(ji.title);
        pr.setText("TK" + Integer.toString(ji.pri) + " only");
        dur.setText(ji.dur);
        tg.setText(ji.tag);
        if (ji.tag != null) {
            switch (ji.tag) {
                case "Most Popular" ->
                    tg.setBackground(new Color(255, 102, 102));
                case "New" ->
                    tg.setBackground(new Color(250, 75, 75));
                case "Recommended" ->
                    tg.setBackground(new Color(255, 102, 102));
                default ->
                    tg.setBackground(new Color(245, 245, 245));
            }
        }

        if (ji.logo != null) {
            ImageIcon imageIcon = new ImageIcon(ji.logo);
            logo.setIcon(imageIcon);
        } else {
            logo.setIcon(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxCustom1 = new try__.JCheckBoxCustom();
        logo = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        textAreaScroll1 = new try__.TextAreaScroll();
        textArea1 = new try__.TextArea();
        jLabel73 = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        jButton57 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        dur = new javax.swing.JLabel();
        tg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 82, 218), 2));

        jCheckBoxCustom1.setText("Enroll Now");
        jCheckBoxCustom1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBoxCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCustom1ActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-applicants-100.png"))); // NOI18N

        ti.setText("PRIORITY APPLICANT");

        textAreaScroll1.setLabelText("");

        textArea1.setColumns(20);
        textArea1.setRows(5);
        textArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textAreaScroll1.setViewportView(textArea1);

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel73.setText("Subscription starts from");

        pr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pr.setText("0tk");

        jButton57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton57.setForeground(new java.awt.Color(0, 153, 255));
        jButton57.setText("Know >");

        dur.setText("jLabel1");

        tg.setBackground(new java.awt.Color(255, 255, 255));
        tg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tg.setForeground(new java.awt.Color(255, 255, 255));
        tg.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(logo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel73))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton57))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ti, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ti, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton57)
                        .addComponent(dur))
                    .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCustom1ActionPerformed
        // TODO add your handling code here:
        showConfirmationDialog();
    }//GEN-LAST:event_jCheckBoxCustom1ActionPerformed

    private void showConfirmationDialog() {
        int result = JOptionPane.showConfirmDialog(
                this, // Parent component (your JFrame)
                "Are you sure you want to Enroll this course?", // Message
                "Confirmation", // Dialog title
                JOptionPane.YES_NO_OPTION // Option type
        );

        if (result == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,"OK! Pay the fee of this course from your profile and start upgrading yourself","ok",JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            // User clicked "No" or closed the dialog
            // Put your code here (if needed)
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dur;
    private javax.swing.JButton jButton57;
    private try__.JCheckBoxCustom jCheckBoxCustom1;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pr;
    private try__.TextArea textArea1;
    private try__.TextAreaScroll textAreaScroll1;
    private javax.swing.JLabel tg;
    private javax.swing.JLabel ti;
    // End of variables declaration//GEN-END:variables
}
