/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drawer;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Hp
 */
public class Overview extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Overview() {
        initComponents();
        showbarchart();
        showPieChart();
        showLineChart();
    }
    private void showbarchart(){
        DefaultCategoryDataset dcd=new DefaultCategoryDataset();
        dcd.setValue(78.70, "Marks", "A");
        dcd.setValue(68.70, "Marks", "B");
        dcd.setValue(88.70, "Marks", "C");
        dcd.setValue(98.70, "Marks", "D");
        dcd.setValue(58.70, "Marks", "E");
        JFreeChart jchart=ChartFactory.createBarChart3D("Student Record", "Student Name", "student marks", dcd, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot plot=jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        ChartPanel chartpanel=new ChartPanel(jchart);
        barchart.removeAll();
        barchart.add(chartpanel);
        barchart.updateUI();
    }
    public void showPieChart() {

        //create dataset
        DefaultPieDataset barDataset = new DefaultPieDataset();

        barDataset.setValue("Accounting", new Double(30));
        barDataset.setValue("IT", new Double(50));
        barDataset.setValue("Design", new Double(30));
        barDataset.setValue("Marketing", new Double(10));
        JFreeChart piechart = ChartFactory.createPieChart("JOB Type", barDataset, false, true, false);//explain

        PiePlot piePlot = (PiePlot) piechart.getPlot();
        piePlot.setSectionPaint("Accounting", new Color(0, 204, 204));
        piePlot.setSectionPaint("IT", new Color(0, 255, 102));
        piePlot.setSectionPaint("Design", new Color(255, 0, 255));
        piePlot.setSectionPaint("Marketing", new Color(255, 255, 0));

        piePlot.setBackgroundPaint(Color.white);

        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        pie.removeAll();
        pie.add(barChartPanel, BorderLayout.CENTER);
        pie.validate();
    }

    public void showLineChart() {
        //create dataset for the graph
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(150, "Amount", "january");
        dataset.setValue(130, "Amount", "february");
        dataset.setValue(16, "Amount", "march");
        dataset.setValue(120, "Amount", "april");
        dataset.setValue(90, "Amount", "may");
        dataset.setValue(200, "Amount", "june");

        JFreeChart linechart = ChartFactory.createLineChart("contribution", "monthly", "amount",
                dataset, PlotOrientation.VERTICAL, false, true, false);

        CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
        lineCategoryPlot.setBackgroundPaint(Color.white);
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(204, 0, 51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        grph.removeAll();
        grph.add(lineChartPanel, BorderLayout.CENTER);
        grph.validate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barchart = new javax.swing.JPanel();
        pie = new javax.swing.JPanel();
        grph = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 770));
        setPreferredSize(new java.awt.Dimension(1500, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barchart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        barchart.setLayout(new java.awt.BorderLayout());
        getContentPane().add(barchart, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 500, 320));

        pie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pie.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 520, 320));

        grph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        grph.setLayout(new java.awt.BorderLayout());
        getContentPane().add(grph, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 500, 320));

        jButton7.setBackground(new java.awt.Color(124, 162, 189));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(10, 13, 118));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/chart_bg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1500, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Admin p = new Admin();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Overview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barchart;
    private javax.swing.JPanel grph;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pie;
    // End of variables declaration//GEN-END:variables
}
