/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drawer;

import careerpathx.ScrollBarCustom;
import dao.ImageIconCellRenderer;
import dao.recruiterdao;
import dao.userdao;
import details.recruiter_info;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.HORIZONTAL;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Recruiter_info extends javax.swing.JFrame {

    Date date = new Date("Jan 1,2001");
    recruiterdao rc = new recruiterdao();
    userdao us = new userdao();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Profile
     */
    public Recruiter_info() {
        initComponents();
        populatetable1();
        init();
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(HORIZONTAL);
        jScrollPane1.setHorizontalScrollBar(sp);
    }

    private void init() {
        jButton4.setEnabled(false);
        uid.setEditable(false);
        dob.setDate(date);
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        uid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        add = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        contact = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new rojeru_san.complementos.RSTableMetro();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dp.setBackground(new java.awt.Color(204, 255, 255));
        dp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dp.setForeground(new java.awt.Color(255, 255, 255));
        dp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 158, 164));

        jButton5.setBackground(new java.awt.Color(67, 67, 158));
        jButton5.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("upload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("User ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 85, 36));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Email :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 85, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 85, 36));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 110, -1));

        pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 300, 40));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 300, 40));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 300, 40));

        uid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 300, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Contact no :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 120, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Date Of Birth :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 150, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Address :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 85, 36));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton1.setText("Female");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 98, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2.setText("Male");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 190, 98, -1));

        add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 310, 40));

        dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 310, 40));

        contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactKeyPressed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 310, 40));

        jButton2.setBackground(new java.awt.Color(67, 67, 158));
        jButton2.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 150, 40));

        jButton1.setBackground(new java.awt.Color(67, 67, 158));
        jButton1.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 130, 40));

        jButton3.setBackground(new java.awt.Color(67, 67, 158));
        jButton3.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, 40));

        jButton4.setBackground(new java.awt.Color(67, 67, 158));
        jButton4.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 120, 40));

        jButton6.setBackground(new java.awt.Color(67, 67, 158));
        jButton6.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View Selected Profile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 310, 40));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtable.setColorBackgoundHead(new java.awt.Color(91, 114, 170));
        jtable.setColorFilasBackgound2(new java.awt.Color(186, 224, 224));
        jtable.setColorFilasForeground1(new java.awt.Color(0, 51, 51));
        jtable.setColorFilasForeground2(new java.awt.Color(0, 51, 51));
        jtable.setColorSelBackgound(new java.awt.Color(90, 174, 174));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1430, 330));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/recruiter_bg.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            dp.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyPressed
        // TODO add your handling code here:
        String phn = contact.getText();
        int l = phn.length();
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
            if (l < 11) {
                contact.setEditable(true);
            } else {
                contact.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                contact.setEditable(true);
            } else {
                contact.setEditable(false);
            }
        }
    }//GEN-LAST:event_contactKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton3.setEnabled(false);
        uid.setText(String.valueOf(rc.getmaxrowj()));
        jButton1.setEnabled(true);
        email.setText("");
        name.setText("");
        pass.setText("");
        contact.setText("");
        dob.setDate(date);
        add.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (infoValid()) {
            int id = rc.getmaxrowj();
            String Email = email.getText();
            String Name = name.getText();
            String password = pass.getText();
            String Contact = contact.getText();
            String address = add.getText();
            String gen = (jRadioButton1.isSelected() ? "Female" : "Male");
            String Dob = "";
            Date selectedDate = dob.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Dob = dateFormat.format(selectedDate);
            Icon icon = dp.getIcon();
            InputStream imgStream = null;
            if (icon != null) {
                BufferedImage bi = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
                Graphics g = bi.createGraphics();
                icon.paintIcon(null, g, 0, 0);
                g.dispose();
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                try {
                    ImageIO.write(bi, "png", baos);
                } catch (IOException ex) {

                }
                imgStream = new ByteArrayInputStream(baos.toByteArray());

            }
            rc.insert(id, Email, Name, password, Contact, address, Dob, gen, imgStream);
            populatetable1();
            jButton1.setEnabled(false);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (infoValid()) {
            int id = Integer.parseInt(uid.getText());
            String Email = email.getText();
            String Name = name.getText();
            String password = pass.getText();
            String Contact = contact.getText();
            String address = add.getText();
            String gen = (jRadioButton1.isSelected() ? "Female" : "Male");
            String Dob = "";
            Date selectedDate = dob.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Dob = dateFormat.format(selectedDate);
            Icon icon = dp.getIcon();
            InputStream imgStream = null;
            if (icon != null) {
                BufferedImage bi = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
                Graphics g = bi.createGraphics();
                icon.paintIcon(null, g, 0, 0);
                g.dispose();
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                try {
                    ImageIO.write(bi, "png", baos);
                } catch (IOException ex) {

                }
                imgStream = new ByteArrayInputStream(baos.toByteArray());

            }
            rc.edit(id, Email, Name, password, Contact, address, Dob, gen, imgStream);
            populatetable1();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selrow = jtable.getSelectedRow();
        int id = (int) model.getValueAt(selrow, 0);
        int n = JOptionPane.showConfirmDialog(this, "Are you Sure you want to delete this?");
        if (n == 0) {
            rc.delete_row(id);
            populatetable1();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public void populatetable1() {
        ArrayList<recruiter_info> list = rc.BindTable();
        String[] colname = {"UserID", "Email", "Name", "pass", "phone", "Address", "Date of Birth", "Gender", "Profile Picture"};
        Object[][] rows = new Object[list.size()][9];
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).getId();
            rows[i][1] = list.get(i).getEmail();
            rows[i][2] = list.get(i).getName();
            rows[i][3] = list.get(i).getPassword();
            rows[i][4] = list.get(i).getPhone();
            rows[i][5] = list.get(i).getAddress();
            rows[i][6] = list.get(i).getDob();
            rows[i][7] = list.get(i).getGender();
            if (list.get(i).getPp() != null) {
                ImageIcon img = new ImageIcon(new ImageIcon(list.get(i).getPp()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
                rows[i][8] = img;
            } else {
                rows[i][8] = null;
            }
        }
        model = new DefaultTableModel(rows, colname) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 8) { // Assuming the "Profile Picture" column is at index 8
                    return ImageIcon.class;
                }
                return super.getColumnClass(columnIndex);
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jtable.setModel(model);
        jtable.setRowHeight(120);
        jtable.getColumnModel().getColumn(8).setCellRenderer(new ImageIconCellRenderer());

    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jseeker_p prf = new jseeker_p();
        prf.setVisible(true);
        prf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        int selrowprof = jtable.getSelectedRow();
        if (selrowprof == -1) {
            prf.jLabellNoselectedRowMessage.setText("No row is selected!");
        } else {
            prf.jLabellNoselectedRowMessage.setText(null);
            prf.jTextField1.setText(model.getValueAt(selrowprof, 0).toString());
            prf.jTextField2.setText(model.getValueAt(selrowprof, 1).toString());
            prf.jTextField3.setText(model.getValueAt(selrowprof, 2).toString());
            prf.jTextField4.setText(model.getValueAt(selrowprof, 3).toString());
            prf.jTextField5.setText(model.getValueAt(selrowprof, 4).toString());
            prf.jTextField6.setText(model.getValueAt(selrowprof, 5).toString());
            prf.jTextField7.setText(model.getValueAt(selrowprof, 6).toString());
            prf.jTextField8.setText(model.getValueAt(selrowprof, 7).toString());
            ImageIcon imgicon = (ImageIcon) model.getValueAt(selrowprof, 8);
            if (imgicon != null) {
                Image imglft = imgicon.getImage().getScaledInstance(dp.getWidth(), dp.getHeight(), Image.SCALE_SMOOTH);
                prf.pp.setIcon(new ImageIcon(imglft));
            } else {
                prf.pp.setIcon(null);
            }
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        jButton4.setEnabled(true);
        jButton1.setEnabled(false);
        int selrow = jtable.getSelectedRow();
        uid.setText(model.getValueAt(selrow, 0).toString());
        email.setText(model.getValueAt(selrow, 1).toString());
        name.setText(model.getValueAt(selrow, 2).toString());
        pass.setText(model.getValueAt(selrow, 3).toString());
        contact.setText(model.getValueAt(selrow, 4).toString());
        add.setText(model.getValueAt(selrow, 5).toString());
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
        try {
            Date dateOfBirth = dateFormat.parse(model.getValueAt(selrow, 6).toString());
            dob.setDate(dateOfBirth);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        if (model.getValueAt(selrow, 7).toString().equals("Female")) {
            jRadioButton1.setSelected(true);
        } else {
            jRadioButton2.setSelected(true);
        }

        ImageIcon imgicon = (ImageIcon) model.getValueAt(selrow, 8);

        if (imgicon != null) {
            Image imglft = imgicon.getImage().getScaledInstance(dp.getWidth(), dp.getHeight(), Image.SCALE_SMOOTH);
            dp.setIcon(new ImageIcon(imglft));
        } else {
            dp.setIcon(null);
        }
    }//GEN-LAST:event_jtableMouseClicked
    public boolean infoValid() {
        if (name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the Phone Number", "Invalid", 2);
            return false;
        } else if (email.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out the Email Address", "Invalid", 2);
            return false;
        } else if (us.isEmailexistr(email.getText())) {
            JOptionPane.showMessageDialog(null, "Email Address is not available", "Invalid", 2);
            return false;
        } else if (!email.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address", "Invalid", 2);
            return false;
        } else if (pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill the Password", "Invalid", 2);
            return false;
        } else if (contact.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill the Phone number", "Invalid", 2);
            return false;
        } else if (us.isPhnexistr(contact.getText())) {
            JOptionPane.showMessageDialog(null, "Phone number is not available", "Invalid", 2);
            return false;
        } else if (add.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill the Address", "Invalid", 2);
            return false;
        }
        return true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recruiter_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recruiter_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recruiter_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recruiter_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recruiter_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField contact;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel dp;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro jtable;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
