/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drawer2;

import First.WrapLayout;
import details.applicant_info;
import java.util.ArrayList;

/**
 *
 * @author Hp
 */
public class AppView extends javax.swing.JPanel {

    /**
     * Creates new form AppView
     */
    ArrayList<applicant_info> job_d;
    int rows = 0;

    public AppView(ArrayList<applicant_info> job_d) {
        initComponents();
        this.job_d = job_d;
        rows = Math.ceilDiv(job_d.size(), 3);
        this.setLayout(new WrapLayout(WrapLayout.LEADING, 80, 80));
        var grid = this;
        //this.setBackground(Color.white);
        for (applicant_info bk: job_d) {
            this.add(new app_view(bk));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
