/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drawer2;

import dao.companydao;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class company_info extends javax.swing.JFrame {

    /**
     * Creates new form company_info
     */
    companydao cmd = new companydao();
    Recruiter rc = new Recruiter();

    public company_info() {
        initComponents();
        web.setEnabled(false);
        up.setEnabled(false);
        up.setVisible(false);
        web.setEditable(false);
        close.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent me) {
                //close.setBackground(Color.RED);
                close.setCursor(new Cursor(Cursor.HAND_CURSOR));
                
            }
        });
        close.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (web.getText().equals("")) {
                    cname.setText((""));
                    ctype.setText((""));
                    loc.setText((""));
                    inds.setText("");
                } else {
                    rc.updateComText(cname.getText());
                }
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cname = new try__.TextField();
        ctype = new try__.TextField();
        loc = new try__.TextField();
        inds = new try__.TextField();
        materialButton1 = new necesario.MaterialButton();
        up = new javax.swing.JButton();
        web = new try__.TextField();
        done = new necesario.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-cross-30.png"))); // NOI18N
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Company Details");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 404, 44));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 351, 111, 76));

        cname.setLabelText("Company name :");
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 56, 315, -1));

        ctype.setLabelText("Company Type :");
        jPanel1.add(ctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 108, 315, -1));

        loc.setLabelText("Location :");
        jPanel1.add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 160, 315, -1));

        inds.setLabelText("Industry :");
        inds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indsActionPerformed(evt);
            }
        });
        jPanel1.add(inds, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 212, 315, -1));

        materialButton1.setBackground(new java.awt.Color(255, 255, 153));
        materialButton1.setText("Next");
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(materialButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 264, 84, 23));

        up.setText("Upload Logo");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 433, 111, -1));

        web.setLabelText("Website");
        jPanel1.add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 293, 315, -1));

        done.setBackground(new java.awt.Color(255, 153, 51));
        done.setForeground(new java.awt.Color(255, 255, 255));
        done.setText("Done!!");
        done.setFont(new java.awt.Font("Roboto Medium", 3, 18)); // NOI18N
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 474, 404, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        setBounds(30, 230, 400, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void indsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indsActionPerformed

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        // TODO add your handling code here:
        done.setEnabled(true);
        String Cname = cname.getText();
        if (!Cname.isEmpty()) {
            if (cmd.isCompanyExist(Cname)) {
                //retrive logo and website
                web.setText(cmd.getwebsite(Cname));
                ImageIcon img = new ImageIcon(new ImageIcon(cmd.getIcon(Cname)).getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img);
            } else {
                web.setEnabled(true);
                up.setEnabled(true);
                up.setVisible(true);
                web.setEditable(true);
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please add Company name", "Invalid", JOptionPane.INFORMATION_MESSAGE);
        }
        

    }//GEN-LAST:event_materialButton1ActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String path = f.getAbsolutePath();
            try {
                BufferedImage bi = ImageIO.read(new File(path));
                Image img = bi.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                jLabel3.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(company_info.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // Handle the case where the user canceled the file selection
            // You can provide a message or perform other actions as needed.
        }
    }//GEN-LAST:event_upActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        if (web.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please add Company Website", "Invalid", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String Cname = cname.getText();
            String Ctype = ctype.getText();
            String Location = loc.getText();
            String Inds = inds.getText();
            String link = web.getText();
            Icon icon = jLabel3.getIcon();
            InputStream imgStream = null;
            if (icon != null) {
                BufferedImage bi = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
                Graphics g = bi.createGraphics();
                icon.paintIcon(null, g, 0, 0);
                g.dispose();
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                try {
                    ImageIO.write(bi, "png", baos);
                } catch (IOException ex) {
                    
                }
                imgStream = new ByteArrayInputStream(baos.toByteArray());
            }
            cmd.insert(Cname, Ctype, Location, Inds, link, imgStream);
            //rc.setVisible(true);
           // rc.updateComText(cname.getText());
           // this.dispose();
        }
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private try__.TextField cname;
    private try__.TextField ctype;
    private necesario.MaterialButton done;
    private try__.TextField inds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private try__.TextField loc;
    private necesario.MaterialButton materialButton1;
    private javax.swing.JButton up;
    private try__.TextField web;
    // End of variables declaration//GEN-END:variables
}
